### ISSUE TITLE
Add WYSIWYG stylesheet

### ISSUE THREAD

**Issue by rbayliss** [LastCallMedia/Drupal-Scaffold#3]
We should automatically generate a stylesheet for use with the WYSIWYG editor.

**Comment by claytron5000** [comment]
Since the ckeditor is the default WYSIWYG editor on D8, I'd assume we're looking to style the ckeditor. It looks like one way to do this is to load a stylesheet through the `.info.yml` file. https://www.drupal.org/developing/api/8/ckeditor
However, I think we're currently set up so Sass compiles all the files into one CSS file. Since a lot of the styles we'd be looking for are included in Foundation this may become a more complicated way of doing things. Perhaps there's a quick way to compile two separate CSS files to avoid loading the entire site CSS into the ckeditor iframe.

**Comment by rbayliss** [comment]
Yep, exactly.  I think it's just a matter of additionally generating a stylesheet that only includes the text styles.  We don't have to use it for the site in general, but we'd load that up in the WYSIWYG.

**Comment by rbayliss** [comment]
Resolved by #5
