### ISSUE TITLE
Help with composer

### ISSUE THREAD

**Issue by smerth** [LastCallMedia/Drupal-Scaffold#42]
Hi there,  I have been developing with Drupal-Scaffold for a couple of months now and installed several modules by composer all with no problem.

I did run composer update recently (I should have specified what to update but I didn't so...)  anyway I am getting this message now when I try to install a module...

```bash
$ composer require drupal/geshifilter
Using version ^1.1 for drupal/geshifilter
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - drupal/console 1.0.0-rc15 requires drupal/console-core 1.0.0-rc15 -> satisfiable by drupal/console-core[1.0.0-rc15].
    - drupal/console 1.0.0-rc15 requires drupal/console-core 1.0.0-rc15 -> satisfiable by drupal/console-core[1.0.0-rc15].
    - drupal/console 1.0.0-rc15 requires drupal/console-core 1.0.0-rc15 -> satisfiable by drupal/console-core[1.0.0-rc15].
    - Removal request for drupal/console-core == 1.0.0.0-RC15
    - Installation request for drupal/console 1.0.0-rc15 -> satisfiable by drupal/console[1.0.0-rc15].


Installation failed, reverting ./composer.json to its original content.
```

I can read this feedback but I don't know what to do about it... Can anyone explain what actions I can take to get past this...

I know this is a composer issue but maybe it has something to do with the configuration of the Drupal-Scaffold...  So, if anyone recognizes the problem and can help me out it would be much appreciated...

Thanks

**Comment by jlandfried** [comment]
Hey @smerth,
Not 100% what's causing that issue, but I think at this point it's safe to change the version constraint for drupal console to something more lenient like `"drupal/console": "~1.0.0",` (this is what I've been using on a project lately and haven't run into any issues with it).

Earlier on we pinned console to rc15 because there were some issues introduced that were preventing builds from working correctly, and there were other issues with contributed modules trying to provide console commands that would cause some fatal errors (metatag's the one that comes to mind), but I haven't seen any of those crop up lately. Maybe try using the constraint for console that I posted above and lmk if you're still seeing issues?

**Comment by smerth** [comment]
Hi @jlandfried,

Thats the conclusion I came to.  I used "drupal/console": "^1.0.0".   

I also changed the minimum stability in my composer.json file to dev.  I try to work with the least number of modules but with Drupal it always seems to be, whatever you want to use, its less than stable when you want to use it!   LOL!  

Thanks for your help.
